services:
  mongodb:
    image: mongo
    container_name: mongodb
    network_mode: "host"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
  backend:
    image: node:latest
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app
    network_mode: "host"
    command: tail -f
    depends_on:
      - mongodb
