services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
    network_mode: "host"
  backend:
    image: node:latest
    container_name: backend
    working_dir: /app
    volumes:
      - .:/app
    network_mode: "host"
    command: tail -f
    depends_on:
      - db